
export type Language = 'en' | 'sw';

export const translations = {
  en: {
    dashboard: 'Dashboard',
    students: 'Students',
    staff: 'Staff',
    attendance: 'Attendance',
    finance: 'Finance',
    reports: 'Transcripts',
    timetable: 'Timetable',
    karibu: 'Welcome',
    total_students: 'Total Students',
    revenue: 'Revenue',
    avg_attendance: 'Avg Attendance',
    pending_reports: 'Pending Reports',
    payment_method: 'Payment Method',
    send_stk: 'Send STK Push',
    record_payment: 'Record Payment',
    sms_alerts: 'SMS Alerts',
    absent_alert: 'Notify parents of absent students',
    fee_balance: 'Fee Balance',
    admission_no: 'Admission No.',
    guardian: 'Guardian',
    save: 'Save',
    cancel: 'Cancel',
    search: 'Search...',
    reconciliation: 'Reconciliation',
    present: 'Present',
    absent: 'Absent',
    late: 'Late',
    mark_all_present: 'Mark All Present',
    mark_all_absent: 'Mark All Absent',
    export_attendance: 'Export Attendance',
    collected_fee: 'Collected Fee',
    outstanding_fees: 'Outstanding Fees',
    prepaid_fees: 'Prepaid Fees',
    total_expected: 'Total Expected'
  },
  sw: {
    dashboard: 'Dahibodi',
    students: 'Wanafunzi',
    staff: 'Wafanyakazi',
    attendance: 'Mahudhurio',
    finance: 'Fedha',
    reports: 'Ripoti',
    timetable: 'Ratiba',
    karibu: 'Karibu',
    total_students: 'Jumla ya Wanafunzi',
    revenue: 'Mapato',
    avg_attendance: 'Mahudhurio Wastani',
    pending_reports: 'Ripoti Zinazosubiri',
    payment_method: 'Njia ya Malipo',
    send_stk: 'Tuma STK Push',
    record_payment: 'Sajili Malipo',
    sms_alerts: 'Arifa za SMS',
    absent_alert: 'Wajulishe wazazi wa wanafunzi wasiofika',
    fee_balance: 'Salio la Ada',
    admission_no: 'Nambari ya Usajili',
    guardian: 'Mlezi',
    save: 'Hifadhi',
    cancel: 'Ghairi',
    search: 'Tafuta...',
    reconciliation: 'Upatanisho',
    present: 'Yupo',
    absent: 'Hayupo',
    late: 'Amechelewa',
    mark_all_present: 'Wote Wapo',
    mark_all_absent: 'Wote Hawapo',
    export_attendance: 'Hamisha Mahudhurio',
    collected_fee: 'Ada Iliyokusanywa',
    outstanding_fees: 'Deni la Ada',
    prepaid_fees: 'Ada Zilizotangulizwa',
    total_expected: 'Jumla Inayotarajiwa'
  }
};
